Test/message signing
vegaprotocol/vegawallet-desktop pull request #180
Opened 2022-02-24 17:25 UTC by jtsang586

Tests to cover recent bug fix for signing message and invalid passphrase

2022-02-25 21:27 UTC, mattrussell36 requested changes

2022-02-25 21:27 UTC, mattrussell36 commented on CHANGELOG.md
> +- Test Cover for message signing
Can we link the PR and fix the typo 'Test cover' => 'Test coverage'

2022-02-28 09:25 UTC, dexturr commented on CHANGELOG.md
> +- Test Cover for message signing
```suggestion
- Test Coverage for message signing
```

2022-02-28 09:26 UTC, dexturr commented on CHANGELOG.md
>  - [](https://github.com/vegaprotocol/vegawallet-desktop/pull/) -
```suggestion
- [180](https://github.com/vegaprotocol/vegawallet-desktop/pull/180) - Test Coverage for message signing
```

2022-02-28 09:31 UTC, jtsang586 commented on CHANGELOG.md
>  - [](https://github.com/vegaprotocol/vegawallet-desktop/pull/) -
Thanks Dexter

2022-02-28 10:05 UTC, dexturr approved these changes

2022-02-28 10:06 UTC, merged